### ISSUE TITLE
[FEAT] 로그 설정 및 회원, 챌린지 엔티티 구현

### ISSUE THREAD

**Issue by Profile-exe** [kakao-tech-campus-2nd-step3/Team15_BE#1]
## 📄 Description
데이터베이스 쿼리 로그 설정 및 회원, 챌린지 엔티티 구현

## ✅ TODO
- [x] `p6spy` 로깅 설정
- [x] `BaseEntity`로 `Auditing` 적용
- [x] 회원 엔티티 구현
- [x] 챌린지 엔티티 구현 (연관관계 매핑)

## 🎸 ETC
[p6spy 로깅 설정](https://curiousjinan.tistory.com/entry/spring-boot-3-p6spy-jpa-logging)
[Spring Data JPA - Auditing](https://velog.io/@wonizizi99/SpringData-JPA-Auditing)
