### ISSUE TITLE
[TEST] TestFixture 설정 및 챌린지 참여 테스트코드 작성

### ISSUE THREAD

**Issue by Profile-exe** [kakao-tech-campus-2nd-step3/Team15_BE#107]
## 📄 Description
- TestFixture 를 만들어서 테스트를 위해 사용하는 데이터(Fixture)들을 생성하는 클래스 구현
- 각 도메인 엔티티에 해당하는 Fixture들로 테스트코드를 작성

## ✅ TODO
- [ ] `gradle`에 `java-test-fixtures` 플러그인 추가
- [ ] 챌린지 및 회원 도메인 `TestFixture` 클래스 작성
- [ ] 챌린지 참여 테스트코드 추가

## 🎸 ETC
TestFixture와 관련해서는 [디스코드 링크](https://discord.com/channels/1280773095325565000/1301435420298580028/1301435420298580028)의 레퍼런스 참고해주세요
