### ISSUE TITLE
[REFACTOR] 챌린지 인증글과 좋아요 엔티티 패키지 변경

### ISSUE THREAD

**Issue by Profile-exe** [kakao-tech-campus-2nd-step3/Team15_BE#12]
## 📄 Description
챌린지 인증글은 `challenge` 패키지로, 좋아요는 `feed` 패키지 내부로 이동

변경 사유
- 챌린지 인증글과 챌린지, 좋아요와 피드 사이에는 강한 연관성이 있음
- 이를 한 패키지에 두어 응집도를 높이고 관련 기능 확장이나 수정 시 쉽게 찾을 수 있음

또한 현재 코드로는 `Book` 엔티티에 대한 import가 제대로 이루어지지 않아 실행이 안되고 있습니다. 해당 부분도 수정 예정입니다.
## ✅ TODO
- [x] 챌린지 인증글, 피드 좋아요 패키지 변경
- [x] 코드 스타일 개선
- [x] 책 엔티티 import 수정
