### ISSUE TITLE
[TEST] 책 테스트 코드 작성

### ISSUE THREAD

**Issue by Wonmoan** [kakao-tech-campus-2nd-step3/Team15_BE#126]
## 📄 Description
- 책 테스트 코드 작성
- FE 요구사항 반영 
  - 책 상세 페이지 리뷰 작성자의 정보 추가
  - 서점 페이지 이동을 위한 `link` api에서 받아오기 
  
## ✅ TODO
- [ ] 책 테스트 코드 작성
- [ ] 작성자 정보 추가 반환
- [ ] 알라딘 api 에서 응답 `link` 추가로 받아오기
