### ISSUE TITLE
[REFACTOR] 위시리스트에 하나의 책 위시만 등록 가능하도록 수정 및 위시 추가, 삭제 시 에러 해결

### ISSUE THREAD

**Issue by seolbin96** [kakao-tech-campus-2nd-step3/Team15_BE#144]
## 📄 Description
위시리스트 수정

## ✅ TODO
- [ ] 한 유저가 하나의 책 위시만 등록 가능하도록 수정
- [ ] 위시리스트 추가 시 204 No Content 대신 200 OK 출력하도록 수정
- [ ] 위시리스트 삭제 시 500 에러 발생하는 부분 해결
