### ISSUE TITLE
[FEAT] 챌린지 참여 API 구현

### ISSUE THREAD

**Issue by Profile-exe** [kakao-tech-campus-2nd-step3/Team15_BE#37]
## 📄 Description

챌린지 참여 및 참여취소 구현

## ✅ TODO
- [ ] 챌린지 참여 구현 
- [ ] 챌린지 참여 취소 구현
- [ ] 챌린지 참여 정보 조회 구현
