### ISSUE TITLE
[FEAT] 위시리스트, 챌린지 인증글 엔티티 구현

### ISSUE THREAD

**Issue by Wonmoan** [kakao-tech-campus-2nd-step3/Team15_BE#4]
## 📄 Description
위시리스트, 챌린지 인증글 엔티티 구현

## ✅ TODO
- [ ] 위시리스트 엔티티 구현
- [ ] 카테고리별 위시리스트 연관관계 매핑 
- [ ] 챌린지 인증글 엔티티 구현
