### ISSUE TITLE
[FEAT] 책 DTO 생성 (best서평, 한줄평 포함) 

### ISSUE THREAD

**Issue by Wonmoan** [kakao-tech-campus-2nd-step3/Team15_BE#42]
## 📄 Description
- 책 DTO를 생성하여 데이터를 전달
- 책 엔티티
  - 출판일자(pub_date) 필드 추가
  - 표지 이미지 필드 `imageUrl` → `cover`로 변경 후 API에서 받아온거 저장
## ✅ TODO
- [ ] 책 정보, best서평, 한줄평을 포함한 dto 생성
- [ ] `RestTemplate`, `ObjectMapper` 방식 수정 
- [ ] ISBN 검색 엔드포인트 수정
- [ ]  책 상세 정보에 들어갈 출판일자(`pub_date`) 필드 추가
- [ ] 표지 이미지 필드의 네이밍 수정 -> `cover`
