### ISSUE TITLE
[FEAT] 비즈니스 예외처리 구현 및 챌린지 도메인에 적용

### ISSUE THREAD

**Issue by Profile-exe** [kakao-tech-campus-2nd-step3/Team15_BE#71]
## 📄 Description
- 비즈니스 예외를 정의하고 예외가 발생한 경우 해당 내용을 클라이언트로 응답해주는 예외처리 구현
- 챌린지 도메인에 비즈니스 예외 적용

## ✅ TODO
- [ ] 최상위 비즈니스 예외와 에러코드 구현
- [ ] 예외처리 핸들러 구현
- [ ] 챌린지 도메인 비즈니스 예외 적용

## 🎸 ETC

- `@Valid` 어노테이션으로 검증을 진행하므로 예외가 발생한 경우 `GlobalExceptionHandler`에서 `handleMethodArgumentNotValid` 메서드를 구현해 검증 예외 정보를 응답하도록 구현

- `BindingResult`의 `FieldError`를 추출해 응답에 포함되도록 구현

  ```java
  private ErrorResponse makeErrorResponse(MethodArgumentNotValidException ex, ErrorCode errorCode) {
      ErrorResponse errorResponse = new ErrorResponse(errorCode);
  
      errorResponse.setInvalidParams(ex.getBindingResult()
              .getFieldErrors()
              .stream()
              .map(ValidationError::of)
              .toList());
  
      return errorResponse;
  }
  ```
