### ISSUE TITLE
[FEAT] 도메인 별 S3 이미지 업로드 및 조회 구현 

### ISSUE THREAD

**Issue by kangboom** [kakao-tech-campus-2nd-step3/Team15_BE#93]
## 📄 Description
각 도메인 별 S3에 이미지 업로드 및 조회가 필요한 부분 구현

## ✅ TODO
- [x] Auth 로그인 시 imageUrl 받아오고 S3에 저장 후 DB에 imageKey 저장
- [ ] Member 관련 조회 presignedUrl 발급
- [ ] 챌린지 및 챌린지 인증 글 생성 시 이미지 업로드 후 imageKey 받아서 생성
- [ ] 챌린지 및 챌린지 인증 글 조회 시 presignedUrl 발급
